# Pandas

In [8]:
import pandas as pd
print(pd.__version__)

2.0.3


# Series

In [15]:
import pandas as pd
arr=[1,2,3,4,5,6,7]
arrnew=pd.Series(arr)
print(arrnew)
print(type(arrnew))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64
<class 'pandas.core.series.Series'>


In [17]:
import pandas as pd
arr=[1,2,3,4,5,6,7]
arrnew=pd.Series(arr, dtype='float', name='python')
print(arrnew)
print(type(arrnew))

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
Name: python, dtype: float64
<class 'pandas.core.series.Series'>


In [18]:
s=pd.Series(12,index=[1,2,3,4,5,6])
print(s)

1    12
2    12
3    12
4    12
5    12
6    12
dtype: int64


In [20]:
s1=pd.Series(12,index=[1,2,3,4,5,6])
s2=pd.Series(12,index=[1,2,3,4])
print(s1+s2)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
dtype: float64


# Labels

In [3]:
print(arrnew[3])

4


In [5]:
a=[1,2,3]
newa=pd.Series(a,index=["x","y","z"])
print(newa)

x    1
y    2
z    3
dtype: int64


In [6]:
print(newa["y"])

2


# Key/Value Objects as Series

In [7]:
mydict={"0":"zero","1":"one","2":"two"}
a=pd.Series(mydict)
print(a)

0    zero
1     one
2     two
dtype: object


In [8]:
mydict={"0":"zero","1":"one","2":"two"}
a=pd.Series(mydict,index=["0","1"])
print(a)

0    zero
1     one
dtype: object


# DataFrames

In [22]:
import pandas as pd
x=[1,2,3,4,5]
xnew=pd.DataFrame(x)
print(xnew)

   0
0  1
1  2
2  3
3  4
4  5


In [10]:
import pandas as pd
x={"No":[0,1,2,3,4,5],"Words":["zero","one","two","three","four","five"]}
xnew=pd.DataFrame(x)
print(xnew)

   No  Words
0   0   zero
1   1    one
2   2    two
3   3  three
4   4   four
5   5   five


In [25]:
import pandas as pd
list_1=[[1,2,3],[4,5,6]]
newlist=pd.DataFrame(list_1)
print(newlist)

   0  1  2
0  1  2  3
1  4  5  6


In [27]:
sr={"s":pd.Series([1,2,3]),"r":pd.Series([1,2,3])}
srnew=pd.DataFrame(sr)
print(srnew)

   s  r
0  1  1
1  2  2
2  3  3


In [23]:
import pandas as pd
x={"No":[0,1,2,3,4,5],"Words":["zero","one","two","three","four","five"]}
xnew=pd.DataFrame(x,columns=["Words"])
print(xnew)

   Words
0   zero
1    one
2    two
3  three
4   four
5   five


In [24]:
print(xnew["Words"][3])

three


# Locate row

In [12]:
import pandas as pd
x={"No":[0,1,2,3,4,5],"Words":["zero","one","two","three","four","five"]}
xnew=pd.DataFrame(x)
print(xnew)

   No  Words
0   0   zero
1   1    one
2   2    two
3   3  three
4   4   four
5   5   five


In [16]:
print(xnew.loc[2])

No         2
Words    two
Name: 2, dtype: object


In [18]:
print(xnew.loc[[1,2]])

   No Words
1   1   one
2   2   two


# Named Indexes

In [19]:
import pandas as pd
x={"No":[1,2,3],"Words":["one","two","three"]}
xnew=pd.DataFrame(x, index=["x","y","z"])
print(xnew)

   No  Words
x   1    one
y   2    two
z   3  three


In [21]:
print(xnew.loc["x"])

No         1
Words    one
Name: x, dtype: object


In [22]:
print(xnew.loc[["x","y"]])

   No Words
x   1   one
y   2   two


# Arithmetic Operations

In [1]:
import pandas as pd
x=pd.DataFrame({"A":[1,2,3],"B":[4,5,6]})
print(x)


   A  B
0  1  4
1  2  5
2  3  6


In [2]:
x["C"]=x["A"]+x["B"]
print(x)

   A  B  C
0  1  4  5
1  2  5  7
2  3  6  9


In [3]:
x["C"]=x["A"]-x["B"]
print(x)

   A  B  C
0  1  4 -3
1  2  5 -3
2  3  6 -3


In [4]:
x["C"]=x["A"]*x["B"]
print(x)

   A  B   C
0  1  4   4
1  2  5  10
2  3  6  18


In [5]:
x["C"]=x["A"]/x["B"]
print(x)

   A  B     C
0  1  4  0.25
1  2  5  0.40
2  3  6  0.50


In [8]:
import pandas as pd
x=pd.DataFrame({"A":[10,20,30,40,50],"B":[14,15,16,17,18]})
x["newA"]=x["A"] >=20
x["newB"]=x["B"] >=16
print(x)

    A   B   newA   newB
0  10  14  False  False
1  20  15   True  False
2  30  16   True   True
3  40  17   True   True
4  50  18   True   True


# Insert

In [9]:
import pandas as pd
x=pd.DataFrame({"A":[1,2,3,4,5], "B":[6,7,8,9,10]})
x.insert(1,"Acopy",x["A"])
print(x)

   A  Acopy   B
0  1      1   6
1  2      2   7
2  3      3   8
3  4      4   9
4  5      5  10


In [10]:
import pandas as pd
x=pd.DataFrame({"A":[1,2,3,4,5], "B":[6,7,8,9,10]})
x["Panda"]=x["A"][:3]
print(x)

   A   B  Panda
0  1   6    1.0
1  2   7    2.0
2  3   8    3.0
3  4   9    NaN
4  5  10    NaN


# Delete

In [13]:
import pandas as pd
x=pd.DataFrame({"A":[1,2,3,4,5], "B":[6,7,8,9,10],"C":[11,12,13,14,15]})
x.pop("B")
print(x)

   A   C
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15


In [14]:
del x["A"]
print(x)

    C
0  11
1  12
2  13
3  14
4  15


# Pandas Read CSV

In [6]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv")
print(myfile)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


# to_string()

In [7]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv")
print(myfile.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

# get particular row

In [17]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv",nrows=1)
print(myfile)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1


# get particular column

In [18]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv",usecols=["Maxpulse"])
print(myfile)

     Maxpulse
0         130
1         145
2         135
3         175
4         148
..        ...
164       140
165       145
166       145
167       150
168       150

[169 rows x 1 columns]


# skip

In [1]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv",skiprows=[0,3])
print(myfile.to_string())

      60  110  130   409.1
0     60  117  145   479.0
1     45  109  175   282.4
2     45  117  148   406.0
3     60  102  127   300.0
4     60  110  136   374.0
5     45  104  134   253.3
6     30  109  133   195.1
7     60   98  124   269.0
8     60  103  147   329.3
9     60  100  120   250.7
10    60  106  128   345.3
11    60  104  132   379.3
12    60   98  123   275.0
13    60   98  120   215.2
14    60  100  120   300.0
15    45   90  112     NaN
16    60  103  123   323.0
17    45   97  125   243.0
18    60  108  131   364.2
19    45  100  119   282.0
20    60  130  101   300.0
21    45  105  132   246.0
22    60  102  126   334.5
23    60  100  120   250.0
24    60   92  118   241.0
25    60  103  132     NaN
26    60  100  132   280.0
27    60  102  129   380.3
28    60   92  115   243.0
29    45   90  112   180.1
30    60  101  124   299.0
31    60   93  113   223.0
32    60  107  136   361.0
33    60  114  140   415.0
34    60  102  127   300.0
35    60  100  120   300.0
3

# Header

In [3]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv", header= 2)
print(myfile.to_string())

      60  117  145     479
0     60  103  135   340.0
1     45  109  175   282.4
2     45  117  148   406.0
3     60  102  127   300.0
4     60  110  136   374.0
5     45  104  134   253.3
6     30  109  133   195.1
7     60   98  124   269.0
8     60  103  147   329.3
9     60  100  120   250.7
10    60  106  128   345.3
11    60  104  132   379.3
12    60   98  123   275.0
13    60   98  120   215.2
14    60  100  120   300.0
15    45   90  112     NaN
16    60  103  123   323.0
17    45   97  125   243.0
18    60  108  131   364.2
19    45  100  119   282.0
20    60  130  101   300.0
21    45  105  132   246.0
22    60  102  126   334.5
23    60  100  120   250.0
24    60   92  118   241.0
25    60  103  132     NaN
26    60  100  132   280.0
27    60  102  129   380.3
28    60   92  115   243.0
29    45   90  112   180.1
30    60  101  124   299.0
31    60   93  113   223.0
32    60  107  136   361.0
33    60  114  140   415.0
34    60  102  127   300.0
35    60  100  120   300.0
3

# index col

In [21]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv",index_col="Duration")
print(myfile)

          Pulse  Maxpulse  Calories
Duration                           
60          110       130     409.1
60          117       145     479.0
60          103       135     340.0
45          109       175     282.4
45          117       148     406.0
...         ...       ...       ...
60          105       140     290.8
60          110       145     300.0
60          115       145     310.2
75          120       150     320.4
75          125       150     330.4

[169 rows x 3 columns]


# names

In [4]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv",names=["col1","col2","col3","col4"])
print(myfile)

         col1   col2      col3      col4
0    Duration  Pulse  Maxpulse  Calories
1          60    110       130     409.1
2          60    117       145       479
3          60    103       135       340
4          45    109       175     282.4
..        ...    ...       ...       ...
165        60    105       140     290.8
166        60    110       145       300
167        60    115       145     310.2
168        75    120       150     320.4
169        75    125       150     330.4

[170 rows x 4 columns]


# dtype

In [8]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv",dtype={"Maxpulse": "float"})
print(myfile)

     Duration  Pulse  Maxpulse  Calories
0          60    110     130.0     409.1
1          60    117     145.0     479.0
2          60    103     135.0     340.0
3          45    109     175.0     282.4
4          45    117     148.0     406.0
..        ...    ...       ...       ...
164        60    105     140.0     290.8
165        60    110     145.0     300.0
166        60    115     145.0     310.2
167        75    120     150.0     320.4
168        75    125     150.0     330.4

[169 rows x 4 columns]


In [14]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv",dtype={"Maxpulse": "f"})
print(myfile.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110     130.0     409.1
1          60    117     145.0     479.0
2          60    103     135.0     340.0
3          45    109     175.0     282.4
4          45    117     148.0     406.0
5          60    102     127.0     300.0
6          60    110     136.0     374.0
7          45    104     134.0     253.3
8          30    109     133.0     195.1
9          60     98     124.0     269.0
10         60    103     147.0     329.3
11         60    100     120.0     250.7
12         60    106     128.0     345.3
13         60    104     132.0     379.3
14         60     98     123.0     275.0
15         60     98     120.0     215.2
16         60    100     120.0     300.0
17         45     90     112.0       NaN
18         60    103     123.0     323.0
19         45     97     125.0     243.0
20         60    108     131.0     364.2
21         45    100     119.0     282.0
22         60    130     101.0     300.0
23         45   

# pandas functions

In [15]:
import pandas as pd

# index

In [17]:
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv")
print(myfile.index)

RangeIndex(start=0, stop=169, step=1)


# columns

In [18]:
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv")
print(myfile.columns)

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')


# describe

In [23]:
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv")
myfile.describe()

Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

# slicing

In [24]:
myfile[:5]

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [25]:
myfile[6:11]

Duration  Pulse  Maxpulse  Calories
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3

# convert index number to an array

In [26]:
myfile.index.array

<PandasArray>
[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
 ...
 159, 160, 161, 162, 163, 164, 165, 166, 167, 168]
Length: 169, dtype: int64

# convert it into numpy

In [27]:
myfile.to_numpy()

array([[  60. ,  110. ,  130. ,  409.1],
       [  60. ,  117. ,  145. ,  479. ],
       [  60. ,  103. ,  135. ,  340. ],
       [  45. ,  109. ,  175. ,  282.4],
       [  45. ,  117. ,  148. ,  406. ],
       [  60. ,  102. ,  127. ,  300. ],
       [  60. ,  110. ,  136. ,  374. ],
       [  45. ,  104. ,  134. ,  253.3],
       [  30. ,  109. ,  133. ,  195.1],
       [  60. ,   98. ,  124. ,  269. ],
       [  60. ,  103. ,  147. ,  329.3],
       [  60. ,  100. ,  120. ,  250.7],
       [  60. ,  106. ,  128. ,  345.3],
       [  60. ,  104. ,  132. ,  379.3],
       [  60. ,   98. ,  123. ,  275. ],
       [  60. ,   98. ,  120. ,  215.2],
       [  60. ,  100. ,  120. ,  300. ],
       [  45. ,   90. ,  112. ,    nan],
       [  60. ,  103. ,  123. ,  323. ],
       [  45. ,   97. ,  125. ,  243. ],
       [  60. ,  108. ,  131. ,  364.2],
       [  45. ,  100. ,  119. ,  282. ],
       [  60. ,  130. ,  101. ,  300. ],
       [  45. ,  105. ,  132. ,  246. ],
       [  60. , 

In [29]:
import numpy as np
v=np.asarray(myfile)
print(v)

[[  60.   110.   130.   409.1]
 [  60.   117.   145.   479. ]
 [  60.   103.   135.   340. ]
 [  45.   109.   175.   282.4]
 [  45.   117.   148.   406. ]
 [  60.   102.   127.   300. ]
 [  60.   110.   136.   374. ]
 [  45.   104.   134.   253.3]
 [  30.   109.   133.   195.1]
 [  60.    98.   124.   269. ]
 [  60.   103.   147.   329.3]
 [  60.   100.   120.   250.7]
 [  60.   106.   128.   345.3]
 [  60.   104.   132.   379.3]
 [  60.    98.   123.   275. ]
 [  60.    98.   120.   215.2]
 [  60.   100.   120.   300. ]
 [  45.    90.   112.     nan]
 [  60.   103.   123.   323. ]
 [  45.    97.   125.   243. ]
 [  60.   108.   131.   364.2]
 [  45.   100.   119.   282. ]
 [  60.   130.   101.   300. ]
 [  45.   105.   132.   246. ]
 [  60.   102.   126.   334.5]
 [  60.   100.   120.   250. ]
 [  60.    92.   118.   241. ]
 [  60.   103.   132.     nan]
 [  60.   100.   132.   280. ]
 [  60.   102.   129.   380.3]
 [  60.    92.   115.   243. ]
 [  45.    90.   112.   180.1]
 [  60. 

# sort into descending order

In [32]:
myfile.sort_index(axis=0,ascending=False)

Duration  Pulse  Maxpulse  Calories
168        75    125       150     330.4
167        75    120       150     320.4
166        60    115       145     310.2
165        60    110       145     300.0
164        60    105       140     290.8
..        ...    ...       ...       ...
4          45    117       148     406.0
3          45    109       175     282.4
2          60    103       135     340.0
1          60    117       145     479.0
0          60    110       130     409.1

[169 rows x 4 columns]

# change the data

In [34]:
myfile.loc[2,"Maxpulse"]=23
print(myfile)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103        23     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


# to get particular columns and rows data

# loc

In [38]:
myfile.loc[[2,3],["Pulse", "Maxpulse"]]

Pulse  Maxpulse
2    103        23
3    109       175

In [41]:
myfile.loc[:,["Pulse", "Maxpulse"]]

Pulse  Maxpulse
0      110       130
1      117       145
2      103        23
3      109       175
4      117       148
..     ...       ...
164    105       140
165    110       145
166    115       145
167    120       150
168    125       150

[169 rows x 2 columns]

# iloc

In [43]:
myfile.iloc[0,1]

110

# drop

# column

In [44]:
myfile.drop("Maxpulse",axis=1)

Duration  Pulse  Calories
0          60    110     409.1
1          60    117     479.0
2          60    103     340.0
3          45    109     282.4
4          45    117     406.0
..        ...    ...       ...
164        60    105     290.8
165        60    110     300.0
166        60    115     310.2
167        75    120     320.4
168        75    125     330.4

[169 rows x 3 columns]

# row

In [46]:
myfile.drop(1,axis=0)

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
2          60    103        23     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[168 rows x 4 columns]

# replace

In [47]:
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv")
myfile.replace(to_replace=60,value=1)

Duration  Pulse  Maxpulse  Calories
0           1    110       130     409.1
1           1    117       145     479.0
2           1    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164         1    105       140     290.8
165         1    110       145     300.0
166         1    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

# ffill

In [53]:
myfile.replace(45,method="ffill")

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          60    109       175     282.4
4          60    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

# bfill

In [54]:
myfile.replace(60,method="bfill")

Duration  Pulse  Maxpulse  Calories
0          45    110       130     409.1
1          45    117       145     479.0
2          45    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        75    105       140     290.8
165        75    110       145     300.0
166        75    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

# limit

In [52]:
myfile.replace(60,method="bfill",limit=2)

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          45    117       145     479.0
2          45    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        75    110       145     300.0
166        75    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [56]:
myfile.replace(60,method="bfill",limit=2,inplace=True)
print(myfile)

     Duration  Pulse  Maxpulse  Calories
0          45    110       130     409.1
1          45    117       145     479.0
2          45    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        75    105       140     290.8
165        75    110       145     300.0
166        75    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


# interpolate

In [59]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv")
print(myfile.interpolate().to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130    409.10
1          60    117       145    479.00
2          60    103       135    340.00
3          45    109       175    282.40
4          45    117       148    406.00
5          60    102       127    300.00
6          60    110       136    374.00
7          45    104       134    253.30
8          30    109       133    195.10
9          60     98       124    269.00
10         60    103       147    329.30
11         60    100       120    250.70
12         60    106       128    345.30
13         60    104       132    379.30
14         60     98       123    275.00
15         60     98       120    215.20
16         60    100       120    300.00
17         45     90       112    311.50
18         60    103       123    323.00
19         45     97       125    243.00
20         60    108       131    364.20
21         45    100       119    282.00
22         60    130       101    300.00
23         45   

In [60]:
print(myfile.interpolate(method="linear").to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130    409.10
1          60    117       145    479.00
2          60    103       135    340.00
3          45    109       175    282.40
4          45    117       148    406.00
5          60    102       127    300.00
6          60    110       136    374.00
7          45    104       134    253.30
8          30    109       133    195.10
9          60     98       124    269.00
10         60    103       147    329.30
11         60    100       120    250.70
12         60    106       128    345.30
13         60    104       132    379.30
14         60     98       123    275.00
15         60     98       120    215.20
16         60    100       120    300.00
17         45     90       112    311.50
18         60    103       123    323.00
19         45     97       125    243.00
20         60    108       131    364.20
21         45    100       119    282.00
22         60    130       101    300.00
23         45   

# merge

In [71]:
import pandas as pd
var1=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
var2=pd.DataFrame({"A":[1,2,3,4,5],"C":[6,7,8,9,10]})
pd.merge(var1,var2)

A   B   C
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [75]:
import pandas as pd
var1=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
var2=pd.DataFrame({"A":[1,2,3,4,5],"C":[6,7,8,9,10]})
pd.merge(var1,var2,on="A")

A   B   C
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [77]:
import pandas as pd
var1=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
var2=pd.DataFrame({"A":[1,2,3,4,5],"C":[6,7,8,9,10]})
pd.merge(var1,var2,on="A",how="left")   #outer,inner,right

A   B   C
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [78]:
import pandas as pd
var1=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
var2=pd.DataFrame({"A":[1,2,3,4,5],"C":[6,7,8,9,10]})
pd.merge(var1,var2,on="A",how="left",indicator=True)

A   B   C _merge
0  1   6   6   both
1  2   7   7   both
2  3   8   8   both
3  4   9   9   both
4  5  10  10   both

In [79]:
import pandas as pd           #for same name
var1=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
var2=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
pd.merge(var1,var2,left_index=True,right_index=True)

A_x  B_x  A_y  B_y
0    1    6    1    6
1    2    7    2    7
2    3    8    3    8
3    4    9    4    9
4    5   10    5   10

In [80]:
import pandas as pd           #for changing name
var1=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
var2=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
pd.merge(var1,var2,left_index=True,right_index=True,suffixes=("name","id"))

Aname  Bname  Aid  Bid
0      1      6    1    6
1      2      7    2    7
2      3      8    3    8
3      4      9    4    9
4      5     10    5   10

# Concat

In [81]:
s1=pd.Series([1,2,3,4])
s2=pd.Series([1,4,6,4])
pd.concat([s1,s2])

0    1
1    2
2    3
3    4
0    1
1    4
2    6
3    4
dtype: int64

In [82]:
import pandas as pd          
var1=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
var2=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
pd.concat([var1,var2],axis=1)

A   B  A   B
0  1   6  1   6
1  2   7  2   7
2  3   8  3   8
3  4   9  4   9
4  5  10  5  10

In [83]:
import pandas as pd          
var1=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
var2=pd.DataFrame({"A":[1,2,3],"B":[6,7,8,]})
pd.concat([var1,var2],axis=1,join="outer")      #union

A   B    A    B
0  1   6  1.0  6.0
1  2   7  2.0  7.0
2  3   8  3.0  8.0
3  4   9  NaN  NaN
4  5  10  NaN  NaN

In [84]:
import pandas as pd          
var1=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
var2=pd.DataFrame({"A":[1,2,3],"B":[6,7,8,]})
pd.concat([var1,var2],axis=1,join="inner")       #intersection

A  B  A  B
0  1  6  1  6
1  2  7  2  7
2  3  8  3  8

In [86]:
import pandas as pd          
var1=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
var2=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
pd.concat([var1,var2],axis=1,keys=["d1","d2"])

d1     d2    
   A   B  A   B
0  1   6  1   6
1  2   7  2   7
2  3   8  3   8
3  4   9  4   9
4  5  10  5  10

# max_rows

In [74]:
import pandas as pd
print(pd.options.display.max_rows)

60


In [9]:
import pandas as pd
pd.options.display.max_rows=999
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv")
print(myfile)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

# Pandas Read JSON

# Dictionary as JSON

In [10]:
import pandas as pd
data={
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}
df = pd.DataFrame(data)
print(df) 

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


# Pandas - Analyzing DataFrames

# head()

In [12]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv")
print(myfile.head(10))

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0


In [15]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv")
print(myfile.head())

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


# tail()

In [13]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv")
print(myfile.tail(10))

     Duration  Pulse  Maxpulse  Calories
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4


In [16]:
import pandas as pd
myfile=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\datasets\data.csv")
print(myfile.tail())

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4


# Info About the Data

In [14]:
print(myfile.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB
None


# Pandas - Cleaning Data

# 1: Cleaning Empty Cells

# Remove Rows

In [9]:
import pandas as pd
raw_data=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\rawdata\Dataset.csv")
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [11]:
cleandata=raw_data.dropna()
print(cleandata.to_string())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [12]:
raw_data.dropna(inplace=True)
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

# Replace Empty Values

In [13]:
import pandas as pd
raw_data=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\rawdata\Dataset.csv")
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [15]:
raw_data.fillna(130, inplace=True)
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

# Replace Only For Specified Columns

In [16]:
import pandas as pd
raw_data=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\rawdata\Dataset.csv")
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [17]:
raw_data["Calories"].fillna(130,inplace=True)
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

# Replace Using Mean, Median, or Mode

# Mean

In [18]:
import pandas as pd
raw_data=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\rawdata\Dataset.csv")
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [20]:
x=raw_data["Calories"].mean()
raw_data["Calories"].fillna(x,inplace=True)
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'  

# Median

In [21]:
import pandas as pd
raw_data=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\rawdata\Dataset.csv")
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [22]:
x=raw_data["Calories"].median()
raw_data["Calories"].fillna(x,inplace=True)
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

# Mode

In [23]:
import pandas as pd
raw_data=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\rawdata\Dataset.csv")
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [24]:
x=raw_data["Calories"].mode()[0]
raw_data["Calories"].fillna(x,inplace=True)
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

# 2: Cleaning Data of Wrong Format


In [1]:
import pandas as pd
raw_data=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\rawdata\Dataset.csv")
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

# Convert Into a Correct Format

In [4]:
import pandas as pd
from dateutil.parser import parse
raw_data=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\rawdata\Dataset.csv")
clean_data=raw_data.copy()
# Convert the 'Date' column to date format using dateutil parser
clean_data["Date"]=clean_data["Date"].apply(lambda x: parse(x) if pd.notnull(x) else x)
# Display the updated DataFrame
print(clean_data)

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90 

# Removing Rows

In [6]:
clean_data.dropna(subset=["Date"],inplace=True)
print(clean_data)

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90 

# 3: Fixing Wrong Data

In [8]:
import pandas as pd
raw_data=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\rawdata\Dataset.csv")
raw_data.loc[7,'Duration']=45
print(raw_data.to_string())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7         45  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

# Using loop

In [11]:
import pandas as pd
raw_data=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\rawdata\Dataset.csv")
for x in raw_data.index:
    if raw_data.loc[x,'Duration'] >120:
        raw_data.loc[x,'Duration']=120   
print(raw_data.to_string())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        120  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

# Removing Rows

In [12]:
import pandas as pd
raw_data=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\rawdata\Dataset.csv")
for i in raw_data.index:
    if raw_data.loc[i,'Duration'] >120:
        raw_data.drop(i,inplace=True)
print(raw_data.to_string())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'  

# 4: Removing Duplicates

# Discovering Duplicates

In [13]:
import pandas as pd
raw_data=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\rawdata\Dataset.csv")
print(raw_data.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool


# Removing Duplicates

In [14]:
raw_data.drop_duplicates(inplace=True)
print(raw_data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'  

# Pandas - Data Correlations


In [5]:
import pandas as pd
from dateutil.parser import parse
raw_data=pd.read_csv(r"C:\Users\Aqsa Kanwal\Desktop\rawdata\Dataset.csv")
clean_data=raw_data.copy()
# Convert the 'Date' column to date format using dateutil parser
clean_data["Date"]=clean_data["Date"].apply(lambda x: parse(x) if pd.notnull(x) else x)
# Display the updated DataFrame
print(clean_data)
print(clean_data.corr())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90 